#!/bin/bash
echo  Starting production build process...
cd /var/www/goatgoat-production/server
mkdir -p logs
echo Running clean...
npm run clean || echo Clean failed continuing...
echo Running build...
npm run build || echo Build had errors continuing...
echo Verifying build...
if [ -f dist/app.js ]; then
    echo ✅ Production build successful - dist/app.js exists
else
    echo ❌ Production build failed - dist/app.js not found
    exit 1
fi
echo 🎉 Production build process completed successfully!
