#!/bin/bash
echo  Starting staging build process...
cd /var/www/goatgoat-staging/server
mkdir -p logs
echo Running clean...
npm run clean || echo Clean failed continuing...
echo Running build...
npm run build || echo Build had errors continuing...
echo Verifying build...
if [ -f dist/app.js ]; then
    echo ✅ Build successful - dist/app.js exists
else
    echo ❌ Build failed - dist/app.js not found
    exit 1
fi
echo 🎉 Build process completed successfully!
